//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnasioTitanes.GYM_BD {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GYM_BD.DataBase_GYMSoap")]
    public interface DataBase_GYMSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPuestos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarPuestos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPuestos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarPuestosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdPuesto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IdPuesto(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdPuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IdPuestoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdSuplemento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IdSuplemento(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdSuplemento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IdSuplementoAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdproveedorMaquinas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IdproveedorMaquinas(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdproveedorMaquinas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IdproveedorMaquinasAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/proveedorSuplemento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet proveedorSuplemento(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/proveedorSuplemento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> proveedorSuplementoAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataBase_GYMSoapChannel : GimnasioTitanes.GYM_BD.DataBase_GYMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBase_GYMSoapClient : System.ServiceModel.ClientBase<GimnasioTitanes.GYM_BD.DataBase_GYMSoap>, GimnasioTitanes.GYM_BD.DataBase_GYMSoap {
        
        public DataBase_GYMSoapClient() {
        }
        
        public DataBase_GYMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBase_GYMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_GYMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBase_GYMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet ListarPuestos() {
            return base.Channel.ListarPuestos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarPuestosAsync() {
            return base.Channel.ListarPuestosAsync();
        }
        
        public System.Data.DataSet IdPuesto(int ID) {
            return base.Channel.IdPuesto(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IdPuestoAsync(int ID) {
            return base.Channel.IdPuestoAsync(ID);
        }
        
        public System.Data.DataSet IdSuplemento(string ID) {
            return base.Channel.IdSuplemento(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IdSuplementoAsync(string ID) {
            return base.Channel.IdSuplementoAsync(ID);
        }
        
        public System.Data.DataSet IdproveedorMaquinas(string ID) {
            return base.Channel.IdproveedorMaquinas(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IdproveedorMaquinasAsync(string ID) {
            return base.Channel.IdproveedorMaquinasAsync(ID);
        }
        
        public System.Data.DataSet proveedorSuplemento(int ID) {
            return base.Channel.proveedorSuplemento(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> proveedorSuplementoAsync(int ID) {
            return base.Channel.proveedorSuplementoAsync(ID);
        }
    }
}
