//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnasioTitanes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_titanesGymEntities : DbContext
    {
        public bd_titanesGymEntities()
            : base("name=bd_titanesGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<planes> planes { get; set; }
        public virtual DbSet<puesto> puesto { get; set; }
        public virtual DbSet<suplemento> suplemento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<ventaSuplemento> ventaSuplemento { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<proveedorMaquinas> proveedorMaquinas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<proveedorSuplemento> proveedorSuplemento { get; set; }
    }
}
