//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnasioTitanes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplemento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suplemento()
        {
            this.ventaSuplemento = new HashSet<ventaSuplemento>();
        }
    
        public int id_suplemento { get; set; }
        public string nom_suplemento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventaSuplemento> ventaSuplemento { get; set; }
    }
}
