//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnasioTitanes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int id_venta { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public string rut_usuario { get; set; }
        public int id_planes { get; set; }
        public int cantidad_venta { get; set; }
        public double valor_venta { get; set; }
    
        public virtual planes planes { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
